### ISSUE TITLE
deleteKnoten(int nr) implementieren

### ISSUE THREAD

**Issue by ts12345** [ts12345/graph#10]
Eingangsparameter prüfen.

Beim Löschen eines Knoten muss beim Knotenfeld und bei der Adjazenzmatrix ein Feld bzw. eine Zeile und eine Spalte gelöscht werden.

Am einfachsten erreicht man das wohl dadurch, dass man ein neues Feld anlegt und nur die notwendigen Knoten kopiert.

Ebenso bei der Matrix.

**Comment by Dudeldu** [comment]
Ich hab das jetzt mal gemacht das es funktioniert. ABER ich habe nicht die Zeile und Spalte der Matrix gelöscht sondern lieber mit -1 überschrieben. Sollte ich Zeile und Spalte löschen würden sich ja alle internen Nummer in der Matrix verschieben und das ist eher nciht so gut glaube ich. Diese Änderung kann auch leicht verträglich gemacht werden, da man nur die erste "leere" Spalte der Matrix beim einfügen suchen muss und dort dann den Eintrag anfügt damit der Speicherbedarf nicht zu hoch steigt. Dazu könnte man die Spalte/Zeile mit -2 füllen damit sie klar als "gelöscht" gekennzeichent ist. Das als Anregung für Mittwoch

**Comment by Dudeldu** [comment]
Da ich noch nicht zum Team gehöre und daher keine Zugriffsberechtigung habe :
[GRAPH.zip](https://github.com/ts12345/graph/files/346777/GRAPH.zip)

**Comment by ts12345** [comment]
Zitat:

...
da man nur die erste "leere" Spalte der Matrix beim einfügen suchen muss und dort dann den Eintrag anfügt damit der Speicherbedarf nicht zu hoch steigt. 
...

Das ist der schwierige Teil. Und kann zu Kopfschmerzen führen. Das kann man folgendermaßen umgehen:

Angenommen, der Knoten mit interner Nummer 3 soll gelöscht werden:

index = 0
Fuer i = 0 bis aktuelle Zahl der Knoten - 1 - 1; i++
  wenn(index == 3) index++
  neuesKnotenfeld[i] = altesKnotenfeld[index]
  index++

Ebenso bei der Adjazenzmatrix.

Anschließend weist man dann das neueKnotenfeld dem aktuellen zu und denkt daran, die aktuelle Zahl der Knoten richtig zu setzen.
