### ISSUE TITLE
#10 und #11 müssten gehen

### ISSUE THREAD

**Issue by Dudeldu** [ts12345/graph#20]
Ich habe nun auch die Knoteneinfügen mEthode dahin verändert, dass sie nicht mehr hinten anfügt sondern im ersten freien feld und delete Knoten ändert das Knotenfeld nun nicht mehr und löscht nur den aktuellen Knoten. Dadurch behalten alle Knoten ihre Nummer und neuen Knoten wird immer eine möglichst niedrige Zahl zugeteilt.
Da ich das restliche System nicht kenne, müsstet ihr den Code ausprobieren.

**Comment by ts12345** [comment]
Die Änderung bei addKnoten muss ich wieder rückgängig machen, ansonsten funktioniert das Anlegen des Graphen in der Klasse TEST nicht.
Es muss noch ein Bug in der Methode sein.

Außerdem rate ich dringend davon ab, das Knotenfeld mit "null" zwischebdurch zu besetzen. Im Augenblick arbeiten wir mit Schleifen

for( int i = 0; i < aktuelleKnotenzahl; i++) 
  knoten[i] ...

und müssten dort überall auf so etwas wie

for( int i = 0; i < maximaleKnotenzahl; i++) 
  if( knoten[i] != null) 

umstellen.
