### ISSUE TITLE
addKnoten(KNOTEN) Eingabeparameter prüfen

### ISSUE THREAD

**Issue by ts12345** [ts12345/graph#3]
Das Einfügen sollte verhindert werden, falls

1) als Eingabewert die null-Referenz übergeben wird.

2) es schon einen Knoten mit der gleichen Bezeichnung (knoten.getBezeichnung) gibt.
Dafür kann die Methode getKnotenIndex verwendet werden

**Comment by hobbyduck** [comment]
Commit ist leider unter #2 gelandet

**Comment by hobbyduck** [comment]
[Hier](https://github.com/ts12345/graph/commit/8c605e9e37596c2d46ab0c1a56ee57610b0af5a9)
